# Packages to be installed via Homebrew
[bootstrap.packages]
# Formulaes
"brew:gnupg" = "latest" # GNU Privacy Guard for encryption and signing
"brew:lcov"  = "latest" # Code coverage tool for C/C++

# Casks
"brew-cask:sublime-text"       = "latest" # Text editor for code, markup and prose
"brew-cask:visual-studio-code" = "latest" # Open-source code editor

# Mac App Store (keyed by ADAM id)
"mas:899247664" = "latest" # TestFlight

# Linter & Formatters
[tools.dprint]
version = "latest"

[tools.taplo]
version = "latest"

[dotfiles]
# dprint & Taplo
"~/.config/dprint.json" = {}
"~/.config/taplo.toml"  = {}

# Gem
"~/.gemrc" = {}

[env]
# Development tools
CHROME_EXECUTABLE           = "${HOME}/Applications/Brave Browser.app/Contents/MacOS/Brave Browser"
DOTNET_CLI_TELEMETRY_OPTOUT = "true"
PRE_COMMIT_HOME             = "${HOME}/.cache/pre-commit"
RUNTIME_ENV                 = "development"

[shell_alias]
# Development related shortcuts
code = "mise run --silent func:code"
edit = "subl"

# Android
adb      = "$ANDROID_HOME/platform-tools/adb"
emulator = "$ANDROID_HOME/emulator/emulator"
