#!/usr/bin/env bash
#MISE description="Restart qdrant (mempalace)"

set -e
source "${HOME}/.config/mise/tasks/_scripts/_helpers"

print_header "Restarting qdrant (mempalace) ..."
mise run mempalace:stop
mise run mempalace:start
